name: My First Workflow
on:  [push]
jobs: 
    first_job: 
        runs-on: ubuntu-latest
        steps: 
        - name: checkout
          uses: actions/checkout@v4

        - name: install node
          run: apt install node

        - name: execute script
          run: node ./prac.js

